### ISSUE TITLE
Vertical alignment of date not centered in today's date on home page

### ISSUE THREAD

**Issue by AndrewFeeney** [YakTrack/YakTrack#135]
<img width="350" alt="Screen Shot 2020-07-31 at 8 38 24 am" src="https://user-images.githubusercontent.com/13425337/88981450-50ae7b80-d309-11ea-9253-8d7c73e50af5.png">

**Comment by stephenhoult** [comment]
Is this still an issue? I believe the homepage may have been updated since this issue was created.

![image](https://user-images.githubusercontent.com/33623309/95783255-6527d080-0cc9-11eb-8c15-afbb3b5e52e9.png)

**Comment by AndrewFeeney** [comment]
@stephenhoult You are correct, this can be closed after recent changes to the home page.
