### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by stephenhoult** [YakTrack/YakTrack#220]
With a freshly cloned repo running `npm install` fails.

Using 
- Node v16.3.0 
- npm v7.15.1

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephen/.npm/_logs/2021-10-04T14_31_19_873Z-debug.log
 ✘  ~/code/personal/YakTrack   develop ±  npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @inertiajs/inertia@0.9.4
npm ERR! node_modules/@inertiajs/inertia
npm ERR!   @inertiajs/inertia@"^0.9.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @inertiajs/inertia@"^0.8.2" from @inertiajs/inertia-vue@0.5.5
npm ERR! node_modules/@inertiajs/inertia-vue
npm ERR!   @inertiajs/inertia-vue@"^0.5.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/stephen/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephen/.npm/_logs/2021-10-04T14_31_30_371Z-debug.log
```

Originally I tried using
- Node v14.16.1
- npm v6.14.12

We get a warning
> his version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

Which suggested I needed to use an updated version of npm (7+).

**Comment by AndrewFeeney** [comment]
Thanks for the issue @stephenhoult. Yeah, I think I've borked the package.json after trying to merge auto-fixes for vulnerabilities without proper care. I'll take a look at this as soon as I can to see if I can get it sorted out.

**Comment by stephenhoult** [comment]
> Thanks for the issue @stephenhoult. Yeah, I think I've borked the package.json after trying to merge auto-fixes for vulnerabilities without proper care. I'll take a look at this as soon as I can to see if I can get it sorted out.

Awesome! I was hoping to get some hacktoberfest PRs in on this repo again this year. 😅

**Comment by AndrewFeeney** [comment]
@stephenhoult The ol' Hacktoberfest Hustle eh? I've pushed a commit which should resolve this. Feel free to reopen the issue if you have any more trouble. https://github.com/YakTrack/YakTrack/commit/bab0174ae3e3a76169512bb1871659beef83409b

**Comment by stephenhoult** [comment]
Thanks @AndrewFeeney 

`npm install` works as expected now, however I'm running into an issue when running `npm run dev`.

```
ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(15:17) The `rounded` class does not exist. If you're sure that `rounded` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  13 | 
  14 | .btn {
> 15 |     @apply px-4 rounded shadow no-underline btn-height;
     |                 ^
  16 | }
  17 | 

```

I can get around this by downgrading tailwind from 2.2.0 to 1.2.0 - but that's probably not the correct fix.

However this seems to be just the tip of the iceberg.

Once all the js / css is compiled and you're logged in there are issues with all navigation links.

E.g. when clicking on the Sessions icon in the sidebar.
![image](https://user-images.githubusercontent.com/33623309/137115336-d5455ff5-a834-4d3f-a6e8-9aa6fad3621c.png)
