### ISSUE TITLE
A user can filter sessions by start time and end time

### ISSUE THREAD

**Issue by AndrewFeeney** [YakTrack/YakTrack#42]

**Comment by DominikSecka** [comment]
Hi @WebSpanner, I would like to work on this issue.

**Comment by AndrewFeeney** [comment]
Hi DominikSecka,

Please do.

**Comment by DominikSecka** [comment]
Thanks for opportunity 😁

**Comment by DominikSecka** [comment]
Hi @WebSpanner, can you change my permissions to project, because I can't push to repository?

**Comment by AndrewFeeney** [comment]
Hi @DominikSecka, you can push your code via a pull request. See here for instructions:

https://help.github.com/articles/creating-a-pull-request/

Thanks!

**Comment by DominikSecka** [comment]
@WebSpanner as far as I know I have to by collaborator on repo to create new branch

**Comment by AndrewFeeney** [comment]
Closed by #89
