### ISSUE TITLE
Convert client/show.blade.php to use show resource table as used in invoice/show.blade.php

### ISSUE THREAD

**Issue by AndrewFeeney** [YakTrack/YakTrack#48]

**Comment by DominikSecka** [comment]
Hi @WebSpanner, I would like to work on this issue.

**Comment by AndrewFeeney** [comment]
Hi DominikSecka,

Go for it!

**Comment by AndrewFeeney** [comment]
Closing as no longer relevant after converting from server rendered application to inertia.js
