### ISSUE TITLE
Edit session page shows time in UTC, but should be display timezone

### ISSUE THREAD

**Issue by AndrewFeeney** [YakTrack/YakTrack#9]

**Comment by Apoorva-13** [comment]
Hey i would like to work on this.
can u help me locate the file in the project where the changes are supposed to made?

**Comment by AndrewFeeney** [comment]
Have at it!

**Comment by AndrewFeeney** [comment]
> can u help me locate the file in the project where the changes are supposed to made?

@Apoorva-13 I'm sorry I missed your edit. Does @sazanrjb's PR and my subsequent commits and review answer your question about which file?

**Comment by AndrewFeeney** [comment]
@Apoorva-13 This has been resolved now, I'm sorry you didn't get the chance to work on it. Feel free to grab any of the other open issues though!
